college = input("Enter ur college name")
city = input("enter ur college city")
contact = input("enter ur contact")
print("college basic details",college+ "" +city)
print("college contact is",contact)
